version: '3.8'

services: 
  backend:
    build: ./backend
    env_file:
      - ./backend/.env 
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: x-files
    ports: 
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



# services: 
#     backend:
#         build: ./backend
#         env_file:
#             - ./backend/.env 
#         ports:
#             - "8000:8000"
#         depends_on:
#             - db
#         command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port" , "8000", "--reload"]
        
#     frontend:
#         build: ./frontend
#         ports:
#             - "5173:5173"
#         command: ["npm" , "run", "dev"]

#     db:
#         image: postgres:latest
#         environment:
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: postgres
#             POSTGRES_DB: x-files
#         ports: 
#             - "5433:5432"
#         volumes: 
#             - postgres_data:/var/lib/postgresql/data

# volumes:
#     postgres_data:
